---
- name: Configure ACL on R3
  hosts: router3
  gather_facts: no
  connection: network_cli


  tasks:
    - name: Configure IPv4 ACL
      cisco.ios.ios_acls:
        state: replaced
        config:
          - afi: ipv4
            acls:
              - name: BLOCK_1_TO_3
                acl_type: extended
                aces:
                  - sequence: 10
                    grant: deny
                    protocol: ip
                    source:
                      host: 10.0.13.1
                    destination:
                      host: 10.0.13.2
                  - sequence: 20
                    grant: permit
                    protocol: ip
                    source:
                      any: true
                    destination:
                      any: true

    - name: Apply ACL inbound on G1
      cisco.ios.ios_acl_interfaces:
        state: merged
        config:
          - name: GigabitEthernet1
            access_groups:
              - afi: ipv4
                acls:
                  - name: BLOCK_1_TO_3
                    direction: in